//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverEmpleado", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverEmpleadoResponse DevolverEmpleado(Proyecto.ServiceReference1.DevolverEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverEmpleadoResponse> DevolverEmpleadoAsync(Proyecto.ServiceReference1.DevolverEmpleadoRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCliente", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverClienteResponse DevolverCliente(Proyecto.ServiceReference1.DevolverClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverClienteResponse> DevolverClienteAsync(Proyecto.ServiceReference1.DevolverClienteRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverDirector", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverDirectorResponse DevolverDirector(Proyecto.ServiceReference1.DevolverDirectorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverDirector", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDirectorResponse> DevolverDirectorAsync(Proyecto.ServiceReference1.DevolverDirectorRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverAdministrador", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverAdministradorResponse DevolverAdministrador(Proyecto.ServiceReference1.DevolverAdministradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverAdministrador", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverAdministradorResponse> DevolverAdministradorAsync(Proyecto.ServiceReference1.DevolverAdministradorRequest request);
        
        // CODEGEN: Generating message contract since element name DevolverNombreClienteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreCliente", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverNombreClienteResponse DevolverNombreCliente(Proyecto.ServiceReference1.DevolverNombreClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreClienteResponse> DevolverNombreClienteAsync(Proyecto.ServiceReference1.DevolverNombreClienteRequest request);
        
        // CODEGEN: Generating message contract since element name DevolverNombreEmpleadoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreEmpleado", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse DevolverNombreEmpleado(Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse> DevolverNombreEmpleadoAsync(Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCasillaCliente", ReplyAction="*")]
        int DevolverCasillaCliente(int pDPI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverCasillaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DevolverCasillaClienteAsync(int pDPI);
        
        // CODEGEN: Generating message contract since element name direccion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParseoCSV", ReplyAction="*")]
        Proyecto.ServiceReference1.ParseoCSVResponse ParseoCSV(Proyecto.ServiceReference1.ParseoCSVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParseoCSV", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.ParseoCSVResponse> ParseoCSVAsync(Proyecto.ServiceReference1.ParseoCSVRequest request);
        
        // CODEGEN: Generating message contract since element name categoria from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarCategoria", ReplyAction="*")]
        Proyecto.ServiceReference1.AgregarCategoriaResponse AgregarCategoria(Proyecto.ServiceReference1.AgregarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.AgregarCategoriaResponse> AgregarCategoriaAsync(Proyecto.ServiceReference1.AgregarCategoriaRequest request);
        
        // CODEGEN: Generating message contract since element name CategoriasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        Proyecto.ServiceReference1.CategoriasResponse Categorias(Proyecto.ServiceReference1.CategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.CategoriasResponse> CategoriasAsync(Proyecto.ServiceReference1.CategoriasRequest request);
        
        // CODEGEN: Generating message contract since element name DevolverDatosClienteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverDatosCliente", ReplyAction="*")]
        Proyecto.ServiceReference1.DevolverDatosClienteResponse DevolverDatosCliente(Proyecto.ServiceReference1.DevolverDatosClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverDatosCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDatosClienteResponse> DevolverDatosClienteAsync(Proyecto.ServiceReference1.DevolverDatosClienteRequest request);
        
        // CODEGEN: Generating message contract since element name pnombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCliente", ReplyAction="*")]
        Proyecto.ServiceReference1.actualizarClienteResponse actualizarCliente(Proyecto.ServiceReference1.actualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.actualizarClienteResponse> actualizarClienteAsync(Proyecto.ServiceReference1.actualizarClienteRequest request);
        
        // CODEGEN: Generating message contract since element name SucursalesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sucursales", ReplyAction="*")]
        Proyecto.ServiceReference1.SucursalesResponse Sucursales(Proyecto.ServiceReference1.SucursalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sucursales", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.SucursalesResponse> SucursalesAsync(Proyecto.ServiceReference1.SucursalesRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCliente", ReplyAction="*")]
        Proyecto.ServiceReference1.RegistrarClienteResponse RegistrarCliente(Proyecto.ServiceReference1.RegistrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.RegistrarClienteResponse> RegistrarClienteAsync(Proyecto.ServiceReference1.RegistrarClienteRequest request);
        
        // CODEGEN: Generating message contract since element name direccion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        Proyecto.ServiceReference1.cargarEmpleadoResponse cargarEmpleado(Proyecto.ServiceReference1.cargarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarEmpleadoResponse> cargarEmpleadoAsync(Proyecto.ServiceReference1.cargarEmpleadoRequest request);
        
        // CODEGEN: Generating message contract since element name direccion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        Proyecto.ServiceReference1.cargarCategoriaResponse cargarCategoria(Proyecto.ServiceReference1.cargarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarCategoriaResponse> cargarCategoriaAsync(Proyecto.ServiceReference1.cargarCategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverEmpleadoRequestBody Body;
        
        public DevolverEmpleadoRequest() {
        }
        
        public DevolverEmpleadoRequest(Proyecto.ServiceReference1.DevolverEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public DevolverEmpleadoRequestBody() {
        }
        
        public DevolverEmpleadoRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverEmpleadoResponseBody Body;
        
        public DevolverEmpleadoResponse() {
        }
        
        public DevolverEmpleadoResponse(Proyecto.ServiceReference1.DevolverEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DevolverEmpleadoResult;
        
        public DevolverEmpleadoResponseBody() {
        }
        
        public DevolverEmpleadoResponseBody(int DevolverEmpleadoResult) {
            this.DevolverEmpleadoResult = DevolverEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverClienteRequestBody Body;
        
        public DevolverClienteRequest() {
        }
        
        public DevolverClienteRequest(Proyecto.ServiceReference1.DevolverClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public DevolverClienteRequestBody() {
        }
        
        public DevolverClienteRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverClienteResponseBody Body;
        
        public DevolverClienteResponse() {
        }
        
        public DevolverClienteResponse(Proyecto.ServiceReference1.DevolverClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DevolverClienteResult;
        
        public DevolverClienteResponseBody() {
        }
        
        public DevolverClienteResponseBody(int DevolverClienteResult) {
            this.DevolverClienteResult = DevolverClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverDirectorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverDirector", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverDirectorRequestBody Body;
        
        public DevolverDirectorRequest() {
        }
        
        public DevolverDirectorRequest(Proyecto.ServiceReference1.DevolverDirectorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverDirectorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public DevolverDirectorRequestBody() {
        }
        
        public DevolverDirectorRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverDirectorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverDirectorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverDirectorResponseBody Body;
        
        public DevolverDirectorResponse() {
        }
        
        public DevolverDirectorResponse(Proyecto.ServiceReference1.DevolverDirectorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverDirectorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DevolverDirectorResult;
        
        public DevolverDirectorResponseBody() {
        }
        
        public DevolverDirectorResponseBody(int DevolverDirectorResult) {
            this.DevolverDirectorResult = DevolverDirectorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverAdministradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverAdministrador", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverAdministradorRequestBody Body;
        
        public DevolverAdministradorRequest() {
        }
        
        public DevolverAdministradorRequest(Proyecto.ServiceReference1.DevolverAdministradorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverAdministradorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public DevolverAdministradorRequestBody() {
        }
        
        public DevolverAdministradorRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverAdministradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverAdministradorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverAdministradorResponseBody Body;
        
        public DevolverAdministradorResponse() {
        }
        
        public DevolverAdministradorResponse(Proyecto.ServiceReference1.DevolverAdministradorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverAdministradorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DevolverAdministradorResult;
        
        public DevolverAdministradorResponseBody() {
        }
        
        public DevolverAdministradorResponseBody(int DevolverAdministradorResult) {
            this.DevolverAdministradorResult = DevolverAdministradorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverNombreClienteRequestBody Body;
        
        public DevolverNombreClienteRequest() {
        }
        
        public DevolverNombreClienteRequest(Proyecto.ServiceReference1.DevolverNombreClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pDPI;
        
        public DevolverNombreClienteRequestBody() {
        }
        
        public DevolverNombreClienteRequestBody(int pDPI) {
            this.pDPI = pDPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverNombreClienteResponseBody Body;
        
        public DevolverNombreClienteResponse() {
        }
        
        public DevolverNombreClienteResponse(Proyecto.ServiceReference1.DevolverNombreClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverNombreClienteResult;
        
        public DevolverNombreClienteResponseBody() {
        }
        
        public DevolverNombreClienteResponseBody(string DevolverNombreClienteResult) {
            this.DevolverNombreClienteResult = DevolverNombreClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverNombreEmpleadoRequestBody Body;
        
        public DevolverNombreEmpleadoRequest() {
        }
        
        public DevolverNombreEmpleadoRequest(Proyecto.ServiceReference1.DevolverNombreEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pNumero;
        
        public DevolverNombreEmpleadoRequestBody() {
        }
        
        public DevolverNombreEmpleadoRequestBody(int pNumero) {
            this.pNumero = pNumero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverNombreEmpleadoResponseBody Body;
        
        public DevolverNombreEmpleadoResponse() {
        }
        
        public DevolverNombreEmpleadoResponse(Proyecto.ServiceReference1.DevolverNombreEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverNombreEmpleadoResult;
        
        public DevolverNombreEmpleadoResponseBody() {
        }
        
        public DevolverNombreEmpleadoResponseBody(string DevolverNombreEmpleadoResult) {
            this.DevolverNombreEmpleadoResult = DevolverNombreEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParseoCSVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParseoCSV", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ParseoCSVRequestBody Body;
        
        public ParseoCSVRequest() {
        }
        
        public ParseoCSVRequest(Proyecto.ServiceReference1.ParseoCSVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParseoCSVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public ParseoCSVRequestBody() {
        }
        
        public ParseoCSVRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParseoCSVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParseoCSVResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.ParseoCSVResponseBody Body;
        
        public ParseoCSVResponse() {
        }
        
        public ParseoCSVResponse(Proyecto.ServiceReference1.ParseoCSVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParseoCSVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto.ServiceReference1.ArrayOfString[] ParseoCSVResult;
        
        public ParseoCSVResponseBody() {
        }
        
        public ParseoCSVResponseBody(Proyecto.ServiceReference1.ArrayOfString[] ParseoCSVResult) {
            this.ParseoCSVResult = ParseoCSVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.AgregarCategoriaRequestBody Body;
        
        public AgregarCategoriaRequest() {
        }
        
        public AgregarCategoriaRequest(Proyecto.ServiceReference1.AgregarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string categoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float porcentaje;
        
        public AgregarCategoriaRequestBody() {
        }
        
        public AgregarCategoriaRequestBody(string categoria, float porcentaje) {
            this.categoria = categoria;
            this.porcentaje = porcentaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.AgregarCategoriaResponseBody Body;
        
        public AgregarCategoriaResponse() {
        }
        
        public AgregarCategoriaResponse(Proyecto.ServiceReference1.AgregarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarCategoriaResult;
        
        public AgregarCategoriaResponseBody() {
        }
        
        public AgregarCategoriaResponseBody(bool AgregarCategoriaResult) {
            this.AgregarCategoriaResult = AgregarCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Categorias", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CategoriasRequestBody Body;
        
        public CategoriasRequest() {
        }
        
        public CategoriasRequest(Proyecto.ServiceReference1.CategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CategoriasRequestBody {
        
        public CategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.CategoriasResponseBody Body;
        
        public CategoriasResponse() {
        }
        
        public CategoriasResponse(Proyecto.ServiceReference1.CategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto.ServiceReference1.ArrayOfString CategoriasResult;
        
        public CategoriasResponseBody() {
        }
        
        public CategoriasResponseBody(Proyecto.ServiceReference1.ArrayOfString CategoriasResult) {
            this.CategoriasResult = CategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverDatosClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverDatosCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverDatosClienteRequestBody Body;
        
        public DevolverDatosClienteRequest() {
        }
        
        public DevolverDatosClienteRequest(Proyecto.ServiceReference1.DevolverDatosClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverDatosClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pDPI;
        
        public DevolverDatosClienteRequestBody() {
        }
        
        public DevolverDatosClienteRequestBody(int pDPI) {
            this.pDPI = pDPI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverDatosClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverDatosClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.DevolverDatosClienteResponseBody Body;
        
        public DevolverDatosClienteResponse() {
        }
        
        public DevolverDatosClienteResponse(Proyecto.ServiceReference1.DevolverDatosClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverDatosClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto.ServiceReference1.ArrayOfString DevolverDatosClienteResult;
        
        public DevolverDatosClienteResponseBody() {
        }
        
        public DevolverDatosClienteResponseBody(Proyecto.ServiceReference1.ArrayOfString DevolverDatosClienteResult) {
            this.DevolverDatosClienteResult = DevolverDatosClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.actualizarClienteRequestBody Body;
        
        public actualizarClienteRequest() {
        }
        
        public actualizarClienteRequest(Proyecto.ServiceReference1.actualizarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pDPI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pnombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string papellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ptelefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pdir;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ptar;
        
        public actualizarClienteRequestBody() {
        }
        
        public actualizarClienteRequestBody(int pDPI, string pnombre, string papellido, string pnit, string ptelefono, string pdir, string ptar) {
            this.pDPI = pDPI;
            this.pnombre = pnombre;
            this.papellido = papellido;
            this.pnit = pnit;
            this.ptelefono = ptelefono;
            this.pdir = pdir;
            this.ptar = ptar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.actualizarClienteResponseBody Body;
        
        public actualizarClienteResponse() {
        }
        
        public actualizarClienteResponse(Proyecto.ServiceReference1.actualizarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int actualizarClienteResult;
        
        public actualizarClienteResponseBody() {
        }
        
        public actualizarClienteResponseBody(int actualizarClienteResult) {
            this.actualizarClienteResult = actualizarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SucursalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sucursales", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.SucursalesRequestBody Body;
        
        public SucursalesRequest() {
        }
        
        public SucursalesRequest(Proyecto.ServiceReference1.SucursalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SucursalesRequestBody {
        
        public SucursalesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SucursalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SucursalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.SucursalesResponseBody Body;
        
        public SucursalesResponse() {
        }
        
        public SucursalesResponse(Proyecto.ServiceReference1.SucursalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SucursalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Proyecto.ServiceReference1.ArrayOfString SucursalesResult;
        
        public SucursalesResponseBody() {
        }
        
        public SucursalesResponseBody(Proyecto.ServiceReference1.ArrayOfString SucursalesResult) {
            this.SucursalesResult = SucursalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarCliente", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.RegistrarClienteRequestBody Body;
        
        public RegistrarClienteRequest() {
        }
        
        public RegistrarClienteRequest(Proyecto.ServiceReference1.RegistrarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pdpi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long tarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contraseña;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sucursal;
        
        public RegistrarClienteRequestBody() {
        }
        
        public RegistrarClienteRequestBody(int pdpi, string nombre, string apellido, long nit, long telefono, string direccion, long tarjeta, string usuario, string contraseña, string sucursal) {
            this.pdpi = pdpi;
            this.nombre = nombre;
            this.apellido = apellido;
            this.nit = nit;
            this.telefono = telefono;
            this.direccion = direccion;
            this.tarjeta = tarjeta;
            this.usuario = usuario;
            this.contraseña = contraseña;
            this.sucursal = sucursal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.RegistrarClienteResponseBody Body;
        
        public RegistrarClienteResponse() {
        }
        
        public RegistrarClienteResponse(Proyecto.ServiceReference1.RegistrarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarClienteResult;
        
        public RegistrarClienteResponseBody() {
        }
        
        public RegistrarClienteResponseBody(bool RegistrarClienteResult) {
            this.RegistrarClienteResult = RegistrarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.cargarEmpleadoRequestBody Body;
        
        public cargarEmpleadoRequest() {
        }
        
        public cargarEmpleadoRequest(Proyecto.ServiceReference1.cargarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarEmpleadoRequestBody() {
        }
        
        public cargarEmpleadoRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.cargarEmpleadoResponseBody Body;
        
        public cargarEmpleadoResponse() {
        }
        
        public cargarEmpleadoResponse(Proyecto.ServiceReference1.cargarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarEmpleadoResponseBody {
        
        public cargarEmpleadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.cargarCategoriaRequestBody Body;
        
        public cargarCategoriaRequest() {
        }
        
        public cargarCategoriaRequest(Proyecto.ServiceReference1.cargarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarCategoriaRequestBody() {
        }
        
        public cargarCategoriaRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto.ServiceReference1.cargarCategoriaResponseBody Body;
        
        public cargarCategoriaResponse() {
        }
        
        public cargarCategoriaResponse(Proyecto.ServiceReference1.cargarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarCategoriaResponseBody {
        
        public cargarCategoriaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Proyecto.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Proyecto.ServiceReference1.Service1Soap>, Proyecto.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverEmpleadoResponse Proyecto.ServiceReference1.Service1Soap.DevolverEmpleado(Proyecto.ServiceReference1.DevolverEmpleadoRequest request) {
            return base.Channel.DevolverEmpleado(request);
        }
        
        public int DevolverEmpleado(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverEmpleadoRequest inValue = new Proyecto.ServiceReference1.DevolverEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverEmpleadoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            Proyecto.ServiceReference1.DevolverEmpleadoResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverEmpleado(inValue);
            return retVal.Body.DevolverEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverEmpleadoResponse> Proyecto.ServiceReference1.Service1Soap.DevolverEmpleadoAsync(Proyecto.ServiceReference1.DevolverEmpleadoRequest request) {
            return base.Channel.DevolverEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverEmpleadoResponse> DevolverEmpleadoAsync(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverEmpleadoRequest inValue = new Proyecto.ServiceReference1.DevolverEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverEmpleadoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverClienteResponse Proyecto.ServiceReference1.Service1Soap.DevolverCliente(Proyecto.ServiceReference1.DevolverClienteRequest request) {
            return base.Channel.DevolverCliente(request);
        }
        
        public int DevolverCliente(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverClienteRequest inValue = new Proyecto.ServiceReference1.DevolverClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverClienteRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            Proyecto.ServiceReference1.DevolverClienteResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverCliente(inValue);
            return retVal.Body.DevolverClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverClienteResponse> Proyecto.ServiceReference1.Service1Soap.DevolverClienteAsync(Proyecto.ServiceReference1.DevolverClienteRequest request) {
            return base.Channel.DevolverClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverClienteResponse> DevolverClienteAsync(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverClienteRequest inValue = new Proyecto.ServiceReference1.DevolverClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverClienteRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverDirectorResponse Proyecto.ServiceReference1.Service1Soap.DevolverDirector(Proyecto.ServiceReference1.DevolverDirectorRequest request) {
            return base.Channel.DevolverDirector(request);
        }
        
        public int DevolverDirector(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverDirectorRequest inValue = new Proyecto.ServiceReference1.DevolverDirectorRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverDirectorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            Proyecto.ServiceReference1.DevolverDirectorResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverDirector(inValue);
            return retVal.Body.DevolverDirectorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDirectorResponse> Proyecto.ServiceReference1.Service1Soap.DevolverDirectorAsync(Proyecto.ServiceReference1.DevolverDirectorRequest request) {
            return base.Channel.DevolverDirectorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDirectorResponse> DevolverDirectorAsync(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverDirectorRequest inValue = new Proyecto.ServiceReference1.DevolverDirectorRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverDirectorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverDirectorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverAdministradorResponse Proyecto.ServiceReference1.Service1Soap.DevolverAdministrador(Proyecto.ServiceReference1.DevolverAdministradorRequest request) {
            return base.Channel.DevolverAdministrador(request);
        }
        
        public int DevolverAdministrador(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverAdministradorRequest inValue = new Proyecto.ServiceReference1.DevolverAdministradorRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverAdministradorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            Proyecto.ServiceReference1.DevolverAdministradorResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverAdministrador(inValue);
            return retVal.Body.DevolverAdministradorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverAdministradorResponse> Proyecto.ServiceReference1.Service1Soap.DevolverAdministradorAsync(Proyecto.ServiceReference1.DevolverAdministradorRequest request) {
            return base.Channel.DevolverAdministradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverAdministradorResponse> DevolverAdministradorAsync(string usuario, string contraseña) {
            Proyecto.ServiceReference1.DevolverAdministradorRequest inValue = new Proyecto.ServiceReference1.DevolverAdministradorRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverAdministradorRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverAdministradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverNombreClienteResponse Proyecto.ServiceReference1.Service1Soap.DevolverNombreCliente(Proyecto.ServiceReference1.DevolverNombreClienteRequest request) {
            return base.Channel.DevolverNombreCliente(request);
        }
        
        public string DevolverNombreCliente(int pDPI) {
            Proyecto.ServiceReference1.DevolverNombreClienteRequest inValue = new Proyecto.ServiceReference1.DevolverNombreClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverNombreClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            Proyecto.ServiceReference1.DevolverNombreClienteResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverNombreCliente(inValue);
            return retVal.Body.DevolverNombreClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreClienteResponse> Proyecto.ServiceReference1.Service1Soap.DevolverNombreClienteAsync(Proyecto.ServiceReference1.DevolverNombreClienteRequest request) {
            return base.Channel.DevolverNombreClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreClienteResponse> DevolverNombreClienteAsync(int pDPI) {
            Proyecto.ServiceReference1.DevolverNombreClienteRequest inValue = new Proyecto.ServiceReference1.DevolverNombreClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverNombreClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverNombreClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse Proyecto.ServiceReference1.Service1Soap.DevolverNombreEmpleado(Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest request) {
            return base.Channel.DevolverNombreEmpleado(request);
        }
        
        public string DevolverNombreEmpleado(int pNumero) {
            Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest inValue = new Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverNombreEmpleadoRequestBody();
            inValue.Body.pNumero = pNumero;
            Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverNombreEmpleado(inValue);
            return retVal.Body.DevolverNombreEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse> Proyecto.ServiceReference1.Service1Soap.DevolverNombreEmpleadoAsync(Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest request) {
            return base.Channel.DevolverNombreEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverNombreEmpleadoResponse> DevolverNombreEmpleadoAsync(int pNumero) {
            Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest inValue = new Proyecto.ServiceReference1.DevolverNombreEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverNombreEmpleadoRequestBody();
            inValue.Body.pNumero = pNumero;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverNombreEmpleadoAsync(inValue);
        }
        
        public int DevolverCasillaCliente(int pDPI) {
            return base.Channel.DevolverCasillaCliente(pDPI);
        }
        
        public System.Threading.Tasks.Task<int> DevolverCasillaClienteAsync(int pDPI) {
            return base.Channel.DevolverCasillaClienteAsync(pDPI);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.ParseoCSVResponse Proyecto.ServiceReference1.Service1Soap.ParseoCSV(Proyecto.ServiceReference1.ParseoCSVRequest request) {
            return base.Channel.ParseoCSV(request);
        }
        
        public Proyecto.ServiceReference1.ArrayOfString[] ParseoCSV(string direccion) {
            Proyecto.ServiceReference1.ParseoCSVRequest inValue = new Proyecto.ServiceReference1.ParseoCSVRequest();
            inValue.Body = new Proyecto.ServiceReference1.ParseoCSVRequestBody();
            inValue.Body.direccion = direccion;
            Proyecto.ServiceReference1.ParseoCSVResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).ParseoCSV(inValue);
            return retVal.Body.ParseoCSVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.ParseoCSVResponse> Proyecto.ServiceReference1.Service1Soap.ParseoCSVAsync(Proyecto.ServiceReference1.ParseoCSVRequest request) {
            return base.Channel.ParseoCSVAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.ParseoCSVResponse> ParseoCSVAsync(string direccion) {
            Proyecto.ServiceReference1.ParseoCSVRequest inValue = new Proyecto.ServiceReference1.ParseoCSVRequest();
            inValue.Body = new Proyecto.ServiceReference1.ParseoCSVRequestBody();
            inValue.Body.direccion = direccion;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).ParseoCSVAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.AgregarCategoriaResponse Proyecto.ServiceReference1.Service1Soap.AgregarCategoria(Proyecto.ServiceReference1.AgregarCategoriaRequest request) {
            return base.Channel.AgregarCategoria(request);
        }
        
        public bool AgregarCategoria(string categoria, float porcentaje) {
            Proyecto.ServiceReference1.AgregarCategoriaRequest inValue = new Proyecto.ServiceReference1.AgregarCategoriaRequest();
            inValue.Body = new Proyecto.ServiceReference1.AgregarCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            inValue.Body.porcentaje = porcentaje;
            Proyecto.ServiceReference1.AgregarCategoriaResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).AgregarCategoria(inValue);
            return retVal.Body.AgregarCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.AgregarCategoriaResponse> Proyecto.ServiceReference1.Service1Soap.AgregarCategoriaAsync(Proyecto.ServiceReference1.AgregarCategoriaRequest request) {
            return base.Channel.AgregarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.AgregarCategoriaResponse> AgregarCategoriaAsync(string categoria, float porcentaje) {
            Proyecto.ServiceReference1.AgregarCategoriaRequest inValue = new Proyecto.ServiceReference1.AgregarCategoriaRequest();
            inValue.Body = new Proyecto.ServiceReference1.AgregarCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            inValue.Body.porcentaje = porcentaje;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).AgregarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.CategoriasResponse Proyecto.ServiceReference1.Service1Soap.Categorias(Proyecto.ServiceReference1.CategoriasRequest request) {
            return base.Channel.Categorias(request);
        }
        
        public Proyecto.ServiceReference1.ArrayOfString Categorias() {
            Proyecto.ServiceReference1.CategoriasRequest inValue = new Proyecto.ServiceReference1.CategoriasRequest();
            inValue.Body = new Proyecto.ServiceReference1.CategoriasRequestBody();
            Proyecto.ServiceReference1.CategoriasResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).Categorias(inValue);
            return retVal.Body.CategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.CategoriasResponse> Proyecto.ServiceReference1.Service1Soap.CategoriasAsync(Proyecto.ServiceReference1.CategoriasRequest request) {
            return base.Channel.CategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.CategoriasResponse> CategoriasAsync() {
            Proyecto.ServiceReference1.CategoriasRequest inValue = new Proyecto.ServiceReference1.CategoriasRequest();
            inValue.Body = new Proyecto.ServiceReference1.CategoriasRequestBody();
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).CategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.DevolverDatosClienteResponse Proyecto.ServiceReference1.Service1Soap.DevolverDatosCliente(Proyecto.ServiceReference1.DevolverDatosClienteRequest request) {
            return base.Channel.DevolverDatosCliente(request);
        }
        
        public Proyecto.ServiceReference1.ArrayOfString DevolverDatosCliente(int pDPI) {
            Proyecto.ServiceReference1.DevolverDatosClienteRequest inValue = new Proyecto.ServiceReference1.DevolverDatosClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverDatosClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            Proyecto.ServiceReference1.DevolverDatosClienteResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverDatosCliente(inValue);
            return retVal.Body.DevolverDatosClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDatosClienteResponse> Proyecto.ServiceReference1.Service1Soap.DevolverDatosClienteAsync(Proyecto.ServiceReference1.DevolverDatosClienteRequest request) {
            return base.Channel.DevolverDatosClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.DevolverDatosClienteResponse> DevolverDatosClienteAsync(int pDPI) {
            Proyecto.ServiceReference1.DevolverDatosClienteRequest inValue = new Proyecto.ServiceReference1.DevolverDatosClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.DevolverDatosClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).DevolverDatosClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.actualizarClienteResponse Proyecto.ServiceReference1.Service1Soap.actualizarCliente(Proyecto.ServiceReference1.actualizarClienteRequest request) {
            return base.Channel.actualizarCliente(request);
        }
        
        public int actualizarCliente(int pDPI, string pnombre, string papellido, string pnit, string ptelefono, string pdir, string ptar) {
            Proyecto.ServiceReference1.actualizarClienteRequest inValue = new Proyecto.ServiceReference1.actualizarClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.actualizarClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            inValue.Body.pnombre = pnombre;
            inValue.Body.papellido = papellido;
            inValue.Body.pnit = pnit;
            inValue.Body.ptelefono = ptelefono;
            inValue.Body.pdir = pdir;
            inValue.Body.ptar = ptar;
            Proyecto.ServiceReference1.actualizarClienteResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).actualizarCliente(inValue);
            return retVal.Body.actualizarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.actualizarClienteResponse> Proyecto.ServiceReference1.Service1Soap.actualizarClienteAsync(Proyecto.ServiceReference1.actualizarClienteRequest request) {
            return base.Channel.actualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.actualizarClienteResponse> actualizarClienteAsync(int pDPI, string pnombre, string papellido, string pnit, string ptelefono, string pdir, string ptar) {
            Proyecto.ServiceReference1.actualizarClienteRequest inValue = new Proyecto.ServiceReference1.actualizarClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.actualizarClienteRequestBody();
            inValue.Body.pDPI = pDPI;
            inValue.Body.pnombre = pnombre;
            inValue.Body.papellido = papellido;
            inValue.Body.pnit = pnit;
            inValue.Body.ptelefono = ptelefono;
            inValue.Body.pdir = pdir;
            inValue.Body.ptar = ptar;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).actualizarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.SucursalesResponse Proyecto.ServiceReference1.Service1Soap.Sucursales(Proyecto.ServiceReference1.SucursalesRequest request) {
            return base.Channel.Sucursales(request);
        }
        
        public Proyecto.ServiceReference1.ArrayOfString Sucursales() {
            Proyecto.ServiceReference1.SucursalesRequest inValue = new Proyecto.ServiceReference1.SucursalesRequest();
            inValue.Body = new Proyecto.ServiceReference1.SucursalesRequestBody();
            Proyecto.ServiceReference1.SucursalesResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).Sucursales(inValue);
            return retVal.Body.SucursalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.SucursalesResponse> Proyecto.ServiceReference1.Service1Soap.SucursalesAsync(Proyecto.ServiceReference1.SucursalesRequest request) {
            return base.Channel.SucursalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.SucursalesResponse> SucursalesAsync() {
            Proyecto.ServiceReference1.SucursalesRequest inValue = new Proyecto.ServiceReference1.SucursalesRequest();
            inValue.Body = new Proyecto.ServiceReference1.SucursalesRequestBody();
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).SucursalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.RegistrarClienteResponse Proyecto.ServiceReference1.Service1Soap.RegistrarCliente(Proyecto.ServiceReference1.RegistrarClienteRequest request) {
            return base.Channel.RegistrarCliente(request);
        }
        
        public bool RegistrarCliente(int pdpi, string nombre, string apellido, long nit, long telefono, string direccion, long tarjeta, string usuario, string contraseña, string sucursal) {
            Proyecto.ServiceReference1.RegistrarClienteRequest inValue = new Proyecto.ServiceReference1.RegistrarClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.RegistrarClienteRequestBody();
            inValue.Body.pdpi = pdpi;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.nit = nit;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            inValue.Body.tarjeta = tarjeta;
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            inValue.Body.sucursal = sucursal;
            Proyecto.ServiceReference1.RegistrarClienteResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).RegistrarCliente(inValue);
            return retVal.Body.RegistrarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.RegistrarClienteResponse> Proyecto.ServiceReference1.Service1Soap.RegistrarClienteAsync(Proyecto.ServiceReference1.RegistrarClienteRequest request) {
            return base.Channel.RegistrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.RegistrarClienteResponse> RegistrarClienteAsync(int pdpi, string nombre, string apellido, long nit, long telefono, string direccion, long tarjeta, string usuario, string contraseña, string sucursal) {
            Proyecto.ServiceReference1.RegistrarClienteRequest inValue = new Proyecto.ServiceReference1.RegistrarClienteRequest();
            inValue.Body = new Proyecto.ServiceReference1.RegistrarClienteRequestBody();
            inValue.Body.pdpi = pdpi;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.nit = nit;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            inValue.Body.tarjeta = tarjeta;
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            inValue.Body.sucursal = sucursal;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).RegistrarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.cargarEmpleadoResponse Proyecto.ServiceReference1.Service1Soap.cargarEmpleado(Proyecto.ServiceReference1.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleado(request);
        }
        
        public void cargarEmpleado(string direccion) {
            Proyecto.ServiceReference1.cargarEmpleadoRequest inValue = new Proyecto.ServiceReference1.cargarEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            Proyecto.ServiceReference1.cargarEmpleadoResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).cargarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarEmpleadoResponse> Proyecto.ServiceReference1.Service1Soap.cargarEmpleadoAsync(Proyecto.ServiceReference1.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarEmpleadoResponse> cargarEmpleadoAsync(string direccion) {
            Proyecto.ServiceReference1.cargarEmpleadoRequest inValue = new Proyecto.ServiceReference1.cargarEmpleadoRequest();
            inValue.Body = new Proyecto.ServiceReference1.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).cargarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto.ServiceReference1.cargarCategoriaResponse Proyecto.ServiceReference1.Service1Soap.cargarCategoria(Proyecto.ServiceReference1.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoria(request);
        }
        
        public void cargarCategoria(string direccion) {
            Proyecto.ServiceReference1.cargarCategoriaRequest inValue = new Proyecto.ServiceReference1.cargarCategoriaRequest();
            inValue.Body = new Proyecto.ServiceReference1.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            Proyecto.ServiceReference1.cargarCategoriaResponse retVal = ((Proyecto.ServiceReference1.Service1Soap)(this)).cargarCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarCategoriaResponse> Proyecto.ServiceReference1.Service1Soap.cargarCategoriaAsync(Proyecto.ServiceReference1.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto.ServiceReference1.cargarCategoriaResponse> cargarCategoriaAsync(string direccion) {
            Proyecto.ServiceReference1.cargarCategoriaRequest inValue = new Proyecto.ServiceReference1.cargarCategoriaRequest();
            inValue.Body = new Proyecto.ServiceReference1.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            return ((Proyecto.ServiceReference1.Service1Soap)(this)).cargarCategoriaAsync(inValue);
        }
    }
}
